module.exports = {
  APPROVAL_STRATEGIES: {
    HIERARCHY: 'HIERARCHY',
    ROLE_BASED: 'ROLE_BASED',
    CUSTOM: 'CUSTOM'
  },

  EXPENSE_STATUS: {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    PAYMENT_PROCESSED: 'PAYMENT_PROCESSED'
  },

  APPROVAL_ACTIONS: {
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    REQUESTED_MODIFICATION: 'REQUESTED_MODIFICATION'
  },

  APPROVAL_LEVELS: {
    EMPLOYEE: 0,
    MANAGER: 1,
    SR_MANAGER: 2,
    DIRECTOR: 3,
    CLEVEL_FINANCE: 4
  },

  ERROR_CODES: {
    ORG_NOT_FOUND: 'ORG_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
    WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
    INVALID_WORKFLOW_STRATEGY: 'INVALID_WORKFLOW_STRATEGY',
    NO_APPROVER_FOUND: 'NO_APPROVER_FOUND',
    UNAUTHORIZED_APPROVAL: 'UNAUTHORIZED_APPROVAL',
    INVALID_EXPENSE_STATUS_TRANSITION: 'INVALID_EXPENSE_STATUS_TRANSITION',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
  },

  HTTP_STATUS_CODES: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500
  }
};
